languageCode = "en-gb"
languageName = "English"
weight = 1
title = "tig's Blog"

[params]
displayName = "EN"
isoCode = "en-gb"
rtl = false
dateFormat = "2 January 2006"
description = "Everything as Code."

[params.author]
name = "tigattack"
headline = "Site Reliability Engineer. Occasional doer of things."
bio = ""
links = [
  { github = "https://github.com/tigattack" },
  { lastfm = "https://www.last.fm/user/tigattack" }
]
image = "tigattack-200.png"
