colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
disableImageOptimization = false
disableTextInHeader = false
defaultBackgroundImage = "background.jpg"
highlightCurrentMenuArea = ""
smartTOCHideUnfocusedChildren = false
smartTOC = true

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = false
homepageImage = "background.jpg"

[article]
editAppendPath = true
heroStyle = "background"
invertPagination = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
seriesOpened = false
showAuthor = true
showAuthorBottom = true
showAuthorsBadges = false
showBreadcrumbs = false
showDate = true
showDateOnlyInArticle = false
showDateUpdated = false
showDraftLabel = true
showEdit = false
showHeadingAnchors = true
showHero = true
showLikes = false
showPagination = true
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showViews = false
showWordCount = true
showZenMode = false
smartTOC = true

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
layoutBackgroundBlur = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]
