# -----------
# Site config
# -----------
baseURL = "https://www.blog.tiga.tech"
title = "tig's Blog"
theme = ["hugo-coder", "hugo-shortcode-gallery"]
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsCodeFences = false
enableEmoji = true

# Enable Disqus comments
# disqusShortname = ""

[params]
author = "tigattack"
description = "Everything as Code."
keywords = "blog,personal,homelab,technology,automotive,cars"
info = ["Systems Engineer", "Breaker of things"]
license = '<a rel="license" href="https://www.gnu.org/licenses/gpl-3.0.en.html">GPL-3.0</a>'
avatarURL = "assets/tigattack-200.png"
favicon_32 = "assets/tigattack-32.png"
favicon_16 = "assets/tigattack-16.png"
dateFormat = "2 January 2006"
since = 2016
# Specify light/dark colorscheme
# "auto" (use browser preference) / "dark" / "light"
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# ------
# Markup
# ------
[markup]
  # Render HTML in markdown
  [markup.goldmark.renderer]
  unsafe= true
  # Set startLevel = 1 to support # title (<h1>title</h1>) otherwise table of content is blank/empty
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

# -----------------
# I8n & page config
# -----------------
[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Posts"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "About"
weight = 3
url = "about/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 4
url = "contact/"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# ------------
# Social links
# ------------
[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/tigattack/"

[[params.social]]
name = "Reddit"
icon = "fa fa-2x fa-reddit-alien"
weight = 1
url = "https://reddit.com/u/tigattack/"

[[params.social]]
name = "Discord"
icon = "fa fa-2x fa-discord"
weight = 1
url = "https://discord.com/users/251776415735873537/"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "/index.xml"
rel = "alternate"
type = "application/rss+xml"

# ---------
# Analytics
# ---------
# More available in theme docs.
# [params.googleTagManager]
# id = "gid"

# ---
# CSP
# ---
[params.csp]
childsrc = ["'self'"]
fontsrc = [
  "'self'",
  "https://fonts.gstatic.com",
  "https://cdn.jsdelivr.net/",
  "https://maxcdn.bootstrapcdn.com" # Required by gh-card shortcode
]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = [
  "'self'",
  "https://avatars.githubusercontent.com", # Required by gh-card shortcode
  "https://opengraph.githubassets.com", # Required by gh-card shortcode
  "data:"
]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/",
  "https://maxcdn.bootstrapcdn.com" # Required by gh-card shortcode
]
scriptsrc = [
  "'self'",
  "'unsafe-inline'",
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/"
]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = [
  "'self'",
  "https://www.google-analytics.com",
  "https://api.github.com" # Required by gh-card shortcode
]
