name: Test and Deploy Hugo site

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  ARTEFACT_NAME: hugo-site
  HUGO_PUBLISHDIR: ./public

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.140.2
      HUGO_CACHEDIR: /tmp/hugo_cache
      HUGO_RESOURCEDIR: /tmp/hugo_resources
    steps:
      - name: Install Hugo CLI
        run: |
          wget -nv -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      # Thanks https://github.com/peaceiris/actions-hugo
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.HUGO_CACHEDIR }}
            ${{ env.HUGO_RESOURCEDIR }}
          key: ${{ runner.os }}-hugo-cache-${{ steps.extract_branch.outputs.branch }}
          restore-keys: |
            ${{ runner.os }}-hugo-cache-

      - uses: actions/configure-pages@v5
        id: pages

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          TZ: Europe/London
        run: |
          hugo \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --minify \
            --gc \
            --logLevel debug \
            --templateMetrics \
            --templateMetricsHints

      - uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ env.ARTEFACT_NAME }}
          path: ${{ env.HUGO_PUBLISHDIR }}

  test:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            tmp/.htmlproofer
            ~/.npm
          key: ${{ runner.os }}-test-cache-deps

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: npm install --save-dev @percy/cli

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTEFACT_NAME }}

      - name: Extract artefact
        run: |
          mkdir $HUGO_PUBLISHDIR
          tar xvf artifact.tar -C $HUGO_PUBLISHDIR

      - run: npx percy snapshot -c .github/percy.yml ${{ env.HUGO_PUBLISHDIR }}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_POSTINSTALL_BROWSER: true

      - uses: chabad360/htmlproofer@v2
        with:
          directory: ${{ env.HUGO_PUBLISHDIR }}
          arguments: >-
            --checks Links,Images,Scripts,Favicon,OpenGraph
            --ignore_missing_alt
            --ignore_status_codes 403
            --typhoeus='{"headers":{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:134.0) Gecko/20100101 Firefox/134.0"}}'
            --cache='{"timeframe": {"external": "30d"}}'

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
        with:
          artifact_name: ${{ env.ARTEFACT_NAME }}
